name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

# softdepend: dynmap

commands:
    warp:
        description: Warp you to a location
        permission: mcsigns.warp
        usage: /<command> warp_name
    warps:
        description: Display list of warps
        permission: mcsigns.warp
        usage: /<command>
    setwarp:
        description: Set a new warp in current location
        permission: mcsigns.warp
        usage: /<command> warp_name
    loc:
        description: Set a new warp in current location
        permission: mcsigns.warp
        usage: /<command> warp_name
    repair:
        description: Repair item in hand
        permission: mcsigns.warp
        usage: /<command>

permissions:
    mcsigns.*:
        description: Gives access to all mcsigns functions
        children: 
            mcsigns.warp: true
            mcsigns.warps: true
            mcsigns.setwarp: true
            mcsigns.loc: true
            mcsigns.repair: true
    mcsigns.warp:
        description: Use warp previously set by /setwarp
        default: true 
    mcsigns.warps:
        description: List all defined warps
        default: true 
    mcsigns.setwarp:
        description: Add warp with specified name /setwarp warp_name
        default: true 
    mcsigns.loc:
        description: Alias for /setwarp. Add warp with specified name /setwarp warp_name
        default: true 
    mcsigns.repair:        
        description: Repair currently held item
        default: true 
